export const SUPPLIER_LIST_REQUEST = 'SUPPLIER_LIST_REQUEST';
export const SUPPLIER_LIST_SUCCESS = 'SUPPLIER_LIST_SUCCESS';
export const SUPPLIER_LIST_FAIL = 'SUPPLIER_LIST_FAIL';

export const SUPPLIER_DETAILS_REQUEST = 'SUPPLIER_DETAILS_REQUEST';
export const SUPPLIER_DETAILS_SUCCESS = 'SUPPLIER_DETAILS_SUCCESS';
export const SUPPLIER_DETAILS_FAIL = 'SUPPLIER_DETAILS_FAIL';

export const SUPPLIER_SAVE_REQUEST = 'SUPPLIER_SAVE_REQUEST';
export const SUPPLIER_SAVE_SUCCESS = 'SUPPLIER_SAVE_SUCCESS';
export const SUPPLIER_SAVE_FAIL = 'SUPPLIER_SAVE_FAIL';

export const SUPPLIER_DELETE_REQUEST = 'SUPPLIER_DELETE_REQUEST';
export const SUPPLIER_DELETE_SUCCESS = 'SUPPLIER_DELETE_SUCCESS';
export const SUPPLIER_DELETE_FAIL = 'SUPPLIER_DELETE_FAIL';

export const SUPPLIER_REVIEW_SAVE_REQUEST = 'SUPPLIER_REVIEW_SAVE_REQUEST';
export const SUPPLIER_REVIEW_SAVE_SUCCESS = 'SUPPLIER_REVIEW_SAVE_SUCCESS';
export const SUPPLIER_REVIEW_SAVE_FAIL = 'SUPPLIER_REVIEW_SAVE_FAIL';
export const SUPPLIER_REVIEW_SAVE_RESET = 'SUPPLIER_REVIEW_SAVE_RESET';
